POST https://your-domain.atlassian.net/rest/api/2/search HTTP/1.1
Host: your-domain.atlassian.net
Accept: application/json
Authorization: Basic blabla==
Content-Type: application/json; charset=utf-8


{
  "fields": [ "*all" ],
  "jql": "project = 'KFX' and sprint in openSprints() ORDER BY key",
  "validateQuery": true,
  "maxResults": 100,
  "startAt": 0
}
###
POST https://your-domain.atlassian.net/rest/api/3/search HTTP/1.1
Host: your-domain.atlassian.net
Accept: application/json
Authorization: Basic blabla==
Content-Type: application/json; charset=utf-8


{
  "fields": [ "*all" ],
  "jql": "project = 'KFX' and sprint in openSprints() ORDER BY key",
  "validateQuery": true,
  "maxResults": 100,
  "startAt": 0
}
###
POST https://your-domain.atlassian.net/rest/api/3/search/jql HTTP/1.1
Host: your-domain.atlassian.net
Accept: application/json
Authorization: Basic blabla==
Content-Type: application/json; charset=utf-8


{
  "expand": "",
  "fields": [ "*all" ],
  "fieldsByKeys": true,
  "jql": "project = 'KFX' and sprint in openSprints() ORDER BY key",
  "maxResults": 100,
  "nextPageToken": ""
}
