jira.client.id=OObevlSfWpZbEl73iTHIyxFIRon0dScj
jira.client.secret=ATOA9bVeIPWSnw4WCFPBue87icr3tZLCWitVE9-CxLrNlCe1ob3uCAy2Wpm8PQ2Y5vYF70EBB1F6
jira.client.redirect.uri=http://localhost:4241/login
khoji-healthcheck.json={\n  \"pushEnabled\": false,\n  \"pushFrequencyInSeconds\": 120,\n  \"vmSubDomain\": \"app.scrumupdate.com\",\n  \"pluginBaseUrl\": \"localhost\",\n  \"monitorPushUrl\": \"https://dummyurl.com/yfuh232\",\n  \"healthCheckExclusions\": [\"jiraPlugin\"]\n}

spring.datasource.username=khoji-admin
spring.datasource.password=khoji
spring.datasource.url=jdbc:postgresql://localhost:5435/khoji-admin?currentSchema=khoji
spring.datasource.hikari.minimumIdle=60
spring.datasource.hikari.maximumPoolSize=60
#When ever we want to load the data, just uncomment the property.
#spring.sql.init.mode=always

server.port=4243
base.url=http://localhost:4241

jwtTokenExpiryMinutes=1440
jwt.secure.random=a9Xk7mLqP1ZvR4NtWc8GpVyJhT5MbQc6LdFsX9YnKrOw2EtHpCgAbVz3JkNpLo7X

khoji.insights.ai.base.url=http://localhost:9090/api/kia