// <auto-generated />
using System;
using KhojiGenAIServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhojiGenAIServer.Migrations
{
    [DbContext(typeof(KGSDbContext))]
    [Migration("20250813163720_DistributedCache")]
    partial class DistributedCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhojiGenAIServer.Data.DistributedCacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("SlidingExpiration")
                        .HasColumnType("interval");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea");

                    b.HasKey("Key");

                    b.ToTable("DistributedCacheEntry", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.TeamUserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MsftTeamsAadObjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PreferredInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MsftTeamsAadObjectId")
                        .IsUnique();

                    b.ToTable("TeamUserPreferences", "kgs");
                });
#pragma warning restore 612, 618
        }
    }
}
