// <auto-generated />
using System;
using KhojiGenAIServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhojiGenAIServer.Migrations
{
    [DbContext(typeof(KGSDbContext))]
    [Migration("20260112165914_LlmCallFailures")]
    partial class LlmCallFailures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "kgs", "job_status", new[] { "pending", "running", "success", "failed", "skipped" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhojiGenAIServer.Data.ConversationReferenceEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceJson")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("ConversationReferenceEntity", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.DistributedCacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("SlidingExpiration")
                        .HasColumnType("interval");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea");

                    b.HasKey("Key");

                    b.ToTable("DistributedCacheEntry", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.JobDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConstructionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("InstanceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRunning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastRunResult")
                        .HasColumnType("text");

                    b.Property<int>("LastRunStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("NextRunTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("JobType", "InstanceId")
                        .IsUnique();

                    b.ToTable("JobDefinitions", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.JobRunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("JobDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime>("RunTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobDefinitionId");

                    b.ToTable("JobRunHistories", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.LlmCallFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LlmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LlmName");

                    b.HasIndex("PromptName");

                    b.HasIndex("StatusCode");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("LlmCallFailures", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.LlmCallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("LlmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PromptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan?>("ResponseTime")
                        .HasColumnType("interval");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LlmName");

                    b.HasIndex("PromptName");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("LlmCallLogs", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.ProactiveSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("InstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("LastFailureMessage")
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionParameters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ServiceType", "ChannelId", "InstanceId", "UserEmail")
                        .IsUnique();

                    b.ToTable("ProactiveSubscriptions", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.StoredKeyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DictionaryName")
                        .HasColumnType("text");

                    b.Property<int>("InstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ValueJson")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "DictionaryName", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_StoredKeyValues_Key_Unique");

                    b.HasIndex("InstanceId", "DictionaryName", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_StoredKeyValues_Order_Unique");

                    b.ToTable("StoredKeyValues", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.TeamUserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MsftTeamsAadObjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PreferredInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MsftTeamsAadObjectId")
                        .IsUnique();

                    b.ToTable("TeamUserPreferences", "kgs");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.JobRunHistory", b =>
                {
                    b.HasOne("KhojiGenAIServer.Data.JobDefinition", "JobDefinition")
                        .WithMany("RunHistory")
                        .HasForeignKey("JobDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDefinition");
                });

            modelBuilder.Entity("KhojiGenAIServer.Data.JobDefinition", b =>
                {
                    b.Navigation("RunHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
