/*
  Copyright 2026 UWorx Services.
  Licensed under the Apache License, Version 2.0.
  See LICENSE for the full license text.
*/

import { Injectable } from '@angular/core';
import html2canvas from 'html2canvas';

@Injectable({
  providedIn: 'root'
})
export class PngExportService {
  constructor() {}

  /**
   * Generate HTML element to PNG canvas with high quality scaling
   */
  async htmlToCanvas(element: HTMLElement, options?: any): Promise<HTMLCanvasElement> {
    return html2canvas(element, {
      scale: window.devicePixelRatio,
      logging: false,
      useCORS: true,
      ...options
    });
  }

  /**
   * Convert canvas to blob and trigger download
   */
  canvasToBlob(canvas: HTMLCanvasElement, filename: string, mimeType: string = 'image/png', quality: number = 0.95): void {
    canvas.toBlob(
      (blob) => {
        if (!blob) {
          console.error('Canvas blob is null');
          return;
        }
        this.downloadBlob(blob, filename);
      },
      mimeType,
      quality
    );
  }

  /**
   * Download blob as file
   */
  private downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Add greyed-out watermark logo to canvas
   * Logo is centered and semi-transparent across entire canvas
   */
  private async addWatermarkToCanvas(canvas: HTMLCanvasElement, logoPath: string): Promise<HTMLCanvasElement> {
    return Promise.resolve(canvas);
  }

  /**
   * Capture dialog with scrollable content as PNG
   * Handles proper height calculation and content expansion
   */
  async captureDialogAsImage(
    dialogContent: HTMLElement,
    filename: string,
    options?: {
      scale?: number;
      allowTaint?: boolean;
      backgroundColor?: string;
      imageTimeout?: number;
      onclone?: (clonedDocument: Document) => void;
    }
  ): Promise<void> {
    // Get dialog dimensions
    const rect = dialogContent.getBoundingClientRect();
    let totalHeight = rect.height + 100;

    // Try to find scrollable content to get actual full height
    const scrollableElement = dialogContent.querySelector('[style*="overflow-y"]') as HTMLElement;
    if (scrollableElement) {
      const scrollHeight = scrollableElement.scrollHeight;
      totalHeight = Math.max(totalHeight, scrollHeight + 200);
    }

    // Wait for any animations to complete and fonts to render
    await new Promise((resolve) => setTimeout(resolve, 300));

    // Capture with device pixel ratio for sharp output
    const canvas = await this.htmlToCanvas(dialogContent, {
      scale: options?.scale || window.devicePixelRatio,
      useCORS: true,
      allowTaint: options?.allowTaint || false,
      logging: false,
      backgroundColor: options?.backgroundColor || '#ffffff',
      imageTimeout: options?.imageTimeout || 5000,
      windowHeight: totalHeight,
      onclone: options?.onclone
    });

    if (!canvas) {
      console.error('Failed to capture canvas');
      return;
    }

    // Add watermark to canvas
    const watermarkedCanvas = await this.addWatermarkToCanvas(canvas, '/assets/images/scrumupdate-logo-v1.svg');

    // Convert canvas to blob and download
    this.canvasToBlob(watermarkedCanvas, filename, 'image/png', 0.95);
  }

  /**
   * Capture dialog with content expansion for full visibility
   * Used for capturing tickets and epics with all details visible
   * Includes footer branding with "Generated by ScrumUpdate on [date] at [time]"
   */
  async captureFullDialogAsImage(dialogContent: HTMLElement, filename: string): Promise<void> {
    // Get the actual full height of the dialog including all expanded content
    const scrollableElement = dialogContent.querySelector('[style*="overflow-y"], .epic-insights-content, .insight-body') as HTMLElement;

    // Calculate total height needed - use scrollHeight to get full content height
    let fullHeight = dialogContent.scrollHeight || dialogContent.offsetHeight;
    if (scrollableElement && scrollableElement.scrollHeight > scrollableElement.offsetHeight) {
      fullHeight = dialogContent.offsetHeight + (scrollableElement.scrollHeight - scrollableElement.offsetHeight);
    }

    const fullWidth = dialogContent.offsetWidth;

    // Wait for rendering
    await new Promise((resolve) => setTimeout(resolve, 150));

    // Capture with html2canvas - preserve all colors and styles
    const canvas = await this.htmlToCanvas(dialogContent, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      logging: false,
      backgroundColor: '#ffffff',
      imageTimeout: 5000,
      windowHeight: fullHeight + 500,
      windowWidth: fullWidth,
      ignoreElements: () => false
    });

    if (!canvas) {
      console.error('Failed to capture canvas');
      return;
    }

    try {
      // Add watermark to canvas
      const watermarkedCanvas = await this.addWatermarkToCanvas(canvas, '/assets/images/scrumupdate-logo-v1.svg');

      // Add footer overlay to canvas
      let newCanvas: HTMLCanvasElement | null = null;
      const ctx = watermarkedCanvas.getContext('2d');
      if (ctx) {
        const footerHeight = 50;
        newCanvas = document.createElement('canvas');
        newCanvas.width = watermarkedCanvas.width;
        newCanvas.height = watermarkedCanvas.height + footerHeight;
        const newCtx = newCanvas.getContext('2d');

        if (newCtx) {
          // Draw original image with watermark
          newCtx.drawImage(watermarkedCanvas, 0, 0);

          // Draw footer background
          newCtx.fillStyle = '#f3f4f6';
          newCtx.fillRect(0, watermarkedCanvas.height, newCanvas.width, footerHeight);

          // Draw footer border
          newCtx.strokeStyle = '#e5e7eb';
          newCtx.lineWidth = 1;
          newCtx.beginPath();
          newCtx.moveTo(0, watermarkedCanvas.height);
          newCtx.lineTo(newCanvas.width, watermarkedCanvas.height);
          newCtx.stroke();

          // Draw footer text - "Generated by ScrumUpdate on [date] at [time]"
          const now = new Date();
          const dateStr = now.toLocaleDateString('en-GB'); // Format: DD/MM/YYYY
          const timeStr = now.toLocaleTimeString('en-GB'); // Format: HH:MM:SS
          const footerText = `Generated by ScrumUpdate on ${dateStr} at ${timeStr}`;

          newCtx.fillStyle = '#6b7280';
          newCtx.font = 'normal 11px Arial, sans-serif';
          newCtx.textAlign = 'center';
          newCtx.textBaseline = 'middle';
          newCtx.fillText(footerText, newCanvas.width / 2, watermarkedCanvas.height + footerHeight / 2);
        }
      }

      // Convert canvas to PNG blob and download
      const finalCanvas = newCanvas || watermarkedCanvas;
      finalCanvas.toBlob(
        (blob) => {
          if (blob) {
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = filename;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
          }
        },
        'image/png',
        1.0
      );
    } catch (error) {
      console.error('Error adding watermark:', error);
      // Fallback: just add footer without watermark
      let newCanvas: HTMLCanvasElement | null = null;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        const footerHeight = 50;
        newCanvas = document.createElement('canvas');
        newCanvas.width = canvas.width;
        newCanvas.height = canvas.height + footerHeight;
        const newCtx = newCanvas.getContext('2d');

        if (newCtx) {
          newCtx.drawImage(canvas, 0, 0);
          newCtx.fillStyle = '#f3f4f6';
          newCtx.fillRect(0, canvas.height, newCanvas.width, footerHeight);
          newCtx.strokeStyle = '#e5e7eb';
          newCtx.lineWidth = 1;
          newCtx.beginPath();
          newCtx.moveTo(0, canvas.height);
          newCtx.lineTo(newCanvas.width, canvas.height);
          newCtx.stroke();

          const now = new Date();
          const dateStr = now.toLocaleDateString('en-GB');
          const timeStr = now.toLocaleTimeString('en-GB');
          const footerText = `Generated by ScrumUpdate on ${dateStr} at ${timeStr}`;
          newCtx.fillStyle = '#6b7280';
          newCtx.font = 'normal 11px Arial, sans-serif';
          newCtx.textAlign = 'center';
          newCtx.textBaseline = 'middle';
          newCtx.fillText(footerText, newCanvas.width / 2, canvas.height + footerHeight / 2);
        }
      }

      const finalCanvas = newCanvas || canvas;
      finalCanvas.toBlob(
        (blob) => {
          if (blob) {
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = filename;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
          }
        },
        'image/png',
        1.0
      );
    }
  }
}
