/*
  Copyright 2026 UWorx Services.
  Licensed under the Apache License, Version 2.0.
  See LICENSE for the full license text.
*/

import { Action, createReducer, on } from '@ngrx/store';
import * as adminActions from 'app/admin/state/admin.actions';
import { setAIGeneratedWorklogSubmissionLoadingState, fetchDailyScrumUpdatesLoadingState, setDeleteWorkLogLoadingState, setEditWorkLogLoadingState, setGenerateAIWorklogLoadingState, setInstanceUserMetaDataLoadingState, setIssueIdValidityLoadingState, setManualWorkLogLoadingState, setPopupGeneratedWorklogSubmissionLoadingState, setWeeklyWorklogSummaryLoadingState, setWorklogSummaryLoadingState, upsertDailyScrumUpdatesLoadingState } from 'app/log-my-work/state/log-my-work.action';
import { LoadingState, LoadingStates } from './app-states';
import * as actions from './app.actions';
import { setFeatureUnlockLoadingState, setWorkLogCategorizationFeatureUnlockLoadingState } from './app.actions';
import { setDeleteAccountLoadingState, setDeleteAppLoadingState } from 'app/user-profile/state/user-profile.actions';
import { setSprintAnalyticsLoadingState } from './sprint-analytics.actions';

;

const loadingStates: LoadingStates = {
  globalStatisticsLoadingState: LoadingState.Pending,
  teamWorklogLoadingState: LoadingState.Pending,
  sourceUsersLoadingState: LoadingState.Pending,
  updateWorkLogEmailLoadingState: LoadingState.Pending,
  worklogCategoryModalClosed: LoadingState.Pending,
  categoryConfigLoadingState: LoadingState.Pending,
  createTeamLoadingState: LoadingState.Pending,
  updateTeamLoadingState: LoadingState.Pending,
  deleteTeamLoadingState: LoadingState.Pending,
  subscriptionDetailsLoadingState: LoadingState.Pending,
  updatedUserProfileLoadingState: LoadingState.Pending,
  updateWorklogRAGEmailState: LoadingState.Pending,
  updateWorklogRAGConfigState: LoadingState.Pending,
  basicUsersLoadingState: LoadingState.Pending,
  assignUserTeamsLoadingState: LoadingState.Pending,
  deleteUserTeamsLoadingState: LoadingState.Pending,
  userDetailLoadingState: LoadingState.Pending,
  teamWorklogForThisMonthLoadingState: LoadingState.Pending,
  billingStrategyLoadingState: LoadingState.Pending,
  assignSupervisorsLoadingState: LoadingState.Pending,
  userProfileLoadingState: LoadingState.Pending,
  teamMembersLoadingState: LoadingState.Pending,
  teamWorkLogSummaryLoadingState: LoadingState.Pending,
  sourceIssueTypesLoadingState: LoadingState.Pending,
  updateOnboardingTeamLoadingState: LoadingState.Pending,
  worklogDistributionLoadingState: LoadingState.Pending,
  requestAccessLoadingState: LoadingState.Pending,
  editUserInBulkLoadingState: LoadingState.Pending,
  membersLoadingState: LoadingState.Pending,
  accountSetupLoadingState: LoadingState.Pending,
  instanceDetailsLoadingState: LoadingState.Pending,
  sendEmailForRemindTeamLoadingState: LoadingState.Pending,
  rolesLoadingState: LoadingState.Pending,
  workspacesLoadingState: LoadingState.Pending,
  accessibleResourcesLoadingState: LoadingState.Pending,
  instanceUserLoadingState: LoadingState.Pending,
  logMyWorkSummaryLoadingState: LoadingState.Pending,
  generateAIWorklogLoadingState: LoadingState.Pending,
  validateUserLoadingState: LoadingState.Pending,
  featureUnlockLoadingState: { featureId: 0, loadingState: LoadingState.Pending },
  validateIssueIdLoadingState: LoadingState.Pending,
  submitAIGeneratedWorklogLoadingState: LoadingState.Pending,
  workLogFeatureUnlockLoadingState: LoadingState.Pending,
  workingHoursPerDayLoadingState: LoadingState.Pending,
  editWorklogLoadingState: LoadingState.Pending,
  deleteWorkLogLoadingState: LoadingState.Pending,
  submitPopupGeneratedWorklogLoadingState: LoadingState.Pending,
  manualWorkLogLoadingState: LoadingState.Pending,
  aiGeneratedCategoriesLoadingState: LoadingState.Pending,
  instanceInviteActionLoadingState: LoadingState.Pending,
  deleteAccountLoadingState: LoadingState.Pending,
  deleteAppLoadingState: LoadingState.Pending,
  weeklyWorklogSummaryLoadingState: LoadingState.Pending,
  fetchDailyScrumLoadingState: LoadingState.Pending,
  upsertDailyScrumLoadingState: LoadingState.Pending,
  linkToMSTeamsLoadingState: LoadingState.Pending,
  dataSyncStatusLoadingState: LoadingState.Pending,
  startDataSyncLoadingState: LoadingState.Pending,
  sprintAnalyticsLoadingState: LoadingState.Pending,
};

const _loadingStatesReducer = createReducer(
  loadingStates,
  on(adminActions.setBillingStrategyLoadingState, (state, { loadingState }) => ({ ...state, billingStrategyLoadingState: loadingState })),
  on(actions.setGlobalStatisticsLoadingState, (state, { globalStatisticsLoadingState }) => ({ ...state, globalStatisticsLoadingState: globalStatisticsLoadingState })),
  on(actions.setTeamWorkLogLoadingState, (state, { teamWorklogLoadingState }) => ({ ...state, teamWorklogLoadingState: teamWorklogLoadingState })),
  on(adminActions.setSourceProjectsLoadingState, (state, { loadingState }) => ({ ...state, sourceProjectsLoadingState: loadingState })),
  on(adminActions.setSourceUsersLoadingState, (state, { loadingState }) => ({ ...state, sourceUsersLoadingState: loadingState })),
  on(adminActions.setBasicUsersLoadingState, (state, { loadingState }) => ({ ...state, basicUsersLoadingState: loadingState })),
  on(adminActions.setAssignTeamsAccessToUserLoadingState, (state, { loadingState }) => ({ ...state, assignUserTeamsLoadingState: loadingState })),
  on(adminActions.setRemoveUserAccessLoadingState, (state, { loadingState }) => ({ ...state, deleteUserTeamsLoadingState: loadingState })),
  on(adminActions.setUserDetailLoadingState, (state, { loadingState }) => ({ ...state, userDetailLoadingState: loadingState })),
  on(adminActions.setSourceUsersLoadingState, (state, { loadingState }) => ({ ...state, sourceUsersLoadingState: loadingState })),
  on(adminActions.setCreateTeamsLoadingState, (state, { loadingState }) => ({ ...state, createTeamLoadingState: loadingState })),
  on(adminActions.setUpdateTeamLoadingState, (state, { loadingState }) => ({ ...state, updateTeamLoadingState: loadingState })),
  on(adminActions.setDeleteTeamsLoadingState, (state, { loadingState }) => ({ ...state, deleteTeamLoadingState: loadingState })),
  on(adminActions.setSourceTeamboardsLoadingState, (state, { loadingState }) => ({ ...state, sourceTeamboardsLoadingState: loadingState })),
  on(actions.setChangePasswordLoadingState, (state, { loadingState }) => ({ ...state, changePasswordLoadingState: loadingState })),
  on(actions.updateWorkLogSettingLoadingState, (state, { loadingState }) => ({ ...state, updateWorkLogEmailLoadingState: loadingState })),
  on(adminActions.setCategoryConfigLoadingState, (state, { loadingState }) => ({ ...state, categoryConfigLoadingState: loadingState, })),
  on(actions.setSubscriptionHostedPageLoadingState, (state, { loadingState }) => ({ ...state, subscriptionDetailsLoadingState: loadingState })),
  on(adminActions.setCategoryConfigLoadingState, (state, { loadingState }) => ({
    ...state,
    categoryConfigLoadingState: loadingState,
  })),
  on(actions.resetLoadingStates, (state) => ({ ...loadingStates, workspacesLoadingState: state.workspacesLoadingState })),
  on(actions.setTenantAdminValidationLoadingState, (state, { loadingState }) => ({ ...state, tenantAdminValidationLoadingState: loadingState })),
  on(actions.setupdateProfileLoadingState, (state, { loadingState }) => ({ ...state, updatedUserProfileLoadingState: loadingState })),
  on(actions.setupdateProfileLoadingState, (state, { loadingState }) => ({ ...state, updatedUserProfileLoadingState: loadingState })),
  on(actions.setWorklogRAGEmailLoadingState, (state, { loadingState }) => ({ ...state, updateWorklogRAGEmailState: loadingState })),
  on(actions.setWorklogRAGConfigLoadingState, (state, { loadingState }) => ({ ...state, updateWorklogRAGConfigState: loadingState })),
  on(actions.setTeamWorkLogForThisMonthLoadingState, (state, { loadingState }) => ({ ...state, teamWorklogForThisMonthLoadingState: loadingState })),
  on(adminActions.setAssignSupervisorsLoadingState, (state, { loadingState }) => ({ ...state, assignSupervisorsLoadingState: loadingState })),
  on(actions.setUserSettingLoadingState, (state, { loadingState }) => ({ ...state, userProfileLoadingState: loadingState })),
  on(actions.setSourceIssueTypesLoadingState, (state, { loadingState }) => ({ ...state, sourceIssueTypesLoadingState: loadingState })),
  on(adminActions.updateOnboardingTeamLoadingState, (state, { loadingState }) => ({ ...state, updateOnboardingTeamLoadingState: loadingState })),
  on(actions.worklogDistributionLoadingState, (state, { loadingState }) => ({ ...state, worklogDistributionLoadingState: loadingState })),
  on(actions.setRequestAccessLoadingState, (state, { loadingState }) => ({ ...state, requestAccessLoadingState: loadingState })),
  on(adminActions.setEditUserInBulkLoadingState, (state, { loadingState }) => ({ ...state, editUserInBulkLoadingState: loadingState })),
  on(adminActions.setMembersLoadingState, (state, { loadingState }) => ({ ...state, membersLoadingState: loadingState })),
  on(adminActions.setSendEmailForWorklogReminderLoadingState, (state, { loadingState }) => ({ ...state, sendEmailForRemindTeamLoadingState: loadingState })),
  on(adminActions.rolesLoadingState, (state, { loadingState }) => ({ ...state, rolesLoadingState: loadingState })),
  on(actions.setWorkspacesLoadingState, (state, { loadingState }) => ({ ...state, workspacesLoadingState: loadingState })),
  on(actions.setInstanceInviteActionLoadingState, (state, { loadingState }) => ({ ...state, instanceInviteActionLoadingState: loadingState })),
  on(actions.setValidateUserLoadingState, (state, { loadingState }) => ({ ...state, validateUserLoadingState: loadingState })),
  on(actions.setAccessibleResourcesLoadingState, (state, { loadingState }) => ({ ...state, accessibleResourcesLoadingState: loadingState })),
  on(actions.setAccountSetupLoadingState, (state, { loading }) => ({ ...state, accountSetupLoadingState: loading })),
  on(actions.setInstanceDetailsLoadingState, (state, { loadingState }) => ({ ...state, instanceDetailsLoadingState: loadingState })),
  on(setInstanceUserMetaDataLoadingState, (state, { loadingState }) => ({ ...state, instanceUserLoadingState: loadingState })),
  on(setWorklogSummaryLoadingState, (state, { loadingState }) => ({ ...state, logMyWorkSummaryLoadingState: loadingState })),
  on(setGenerateAIWorklogLoadingState, (state, { loadingState }) => ({ ...state, generateAIWorklogLoadingState: loadingState })),
  on(setIssueIdValidityLoadingState, (state, { loadingState }) => ({ ...state, validateIssueIdLoadingState: loadingState })),
  on(setAIGeneratedWorklogSubmissionLoadingState, (state, { loadingState }) => ({ ...state, submitAIGeneratedWorklogLoadingState: loadingState })),
  on(setManualWorkLogLoadingState, (state, { loadingState }) => ({ ...state, manualWorkLogLoadingState: loadingState })),
  on(setPopupGeneratedWorklogSubmissionLoadingState, (state, { loadingState }) => ({ ...state, submitPopupGeneratedWorklogLoadingState: loadingState })),
  on(setEditWorkLogLoadingState, (state, { loadingState }) => ({ ...state, editWorklogLoadingState: loadingState })),
  on(setDeleteWorkLogLoadingState, (state, { loadingState }) => ({ ...state, deleteWorkLogLoadingState: loadingState })),
  on(setWorklogSummaryLoadingState, (state, { loadingState }) => ({ ...state, logMyWorkSummaryLoadingState: loadingState })),
  on(setFeatureUnlockLoadingState, (state, { featureId, loadingState }) => ({ ...state, featureUnlockLoadingState: { featureId, loadingState } })),
  on(setWorkLogCategorizationFeatureUnlockLoadingState, (state, { loadingState }) => ({ ...state, workLogFeatureUnlockLoadingState: loadingState })),
  on(actions.WorkingHourPerDayConfigLoadingState, (state, { loadingState }) => ({ ...state, workingHoursPerDayLoadingState: loadingState })),
  on(actions.setAiGeneratedCategoriesLoadingState, (state, { loadingState }) => ({ ...state, aiGeneratedCategoriesLoadingState: loadingState })),
  on(setDeleteAccountLoadingState, (state, { loading }) => ({ ...state, deleteAccountLoadingState: loading })),
  on(setDeleteAppLoadingState, (state, { loading }) => ({ ...state, deleteAppLoadingState: loading })),
  on(setWeeklyWorklogSummaryLoadingState, (state, { loading }) => ({ ...state, weeklyWorklogSummaryLoadingState: loading })),
  on(fetchDailyScrumUpdatesLoadingState, (state, { loading }) => ({ ...state, fetchDailyScrumLoadingState: loading })),
  on(upsertDailyScrumUpdatesLoadingState, (state, { loading }) => ({ ...state, upsertDailyScrumLoadingState: loading })),
  on(actions.setAiGeneratedCategoriesLoadingState, (state, { loadingState }) => ({ ...state, aiGeneratedCategoriesLoadingState: loadingState })),
  on(actions.setLinkToMSTeamsLoadingState, (state, { loadingState }) => ({ ...state, linkToMSTeamsLoadingState: loadingState })),
  on(actions.clearStatesForLoginPage, (state) => ({ ...loadingStates })),
  on(setSprintAnalyticsLoadingState, (state, { sprintAnalyticsLoadingState }) => ({ ...state, sprintAnalyticsLoadingState })),
);
export function loadingStatesReducer(state: LoadingStates, action: Action) {
  return _loadingStatesReducer(state, action);
}
